# Form implementation generated from reading ui file 'flights.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog

class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QDialog {\n"
"background-color: yellow\n"
"}\n"
"QLabel {\n"
"color: green\n"
"}")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 40, 281, 221))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_first = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.radioButton_first.setFont(font)
        self.radioButton_first.setObjectName("radioButton_first")

        self.radioButton_first.toggled.connect(self.radio_selected)
        self.verticalLayout.addWidget(self.radioButton_first)
        self.radioButton_second = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.radioButton_second.setFont(font)
        self.radioButton_second.setObjectName("radioButton_second")
        self.radioButton_second.toggled.connect(self.radio_selected)

        self.verticalLayout.addWidget(self.radioButton_second)
        self.radioButton_third = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.radioButton_third.setFont(font)
        self.radioButton_third.setObjectName("radioButton_third")
        self.radioButton_third.toggled.connect(self.radio_selected)

        self.verticalLayout.addWidget(self.radioButton_third)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.labelresult = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelresult.setFont(font)
        self.labelresult.setObjectName("labelresult")
        self.verticalLayout_3.addWidget(self.labelresult)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_selected(self):
        radio_btn = self.sender()
        if radio_btn.isChecked():
            self.labelresult.setText("You've selected: {} ".format(radio_btn.text()))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Select Flight Type"))
        self.radioButton_first.setText(_translate("Dialog", "First Class           $150"))
        self.radioButton_second.setText(_translate("Dialog", "Second Class      $100"))
        self.radioButton_third.setText(_translate("Dialog", "Third Class          $50"))
        self.labelresult.setText(_translate("Dialog", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
