# Form implementation generated from reading ui file 'spinboxdemo.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditPenPrice = QtWidgets.QLineEdit(Form)
        self.lineEditPenPrice.setObjectName("lineEditPenPrice")
        self.horizontalLayout.addWidget(self.lineEditPenPrice)
        self.spinBox = QtWidgets.QSpinBox(Form)

        #connect to signal
        self.spinBox.editingFinished.connect(self.first_result)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.lineEditTotalPen = QtWidgets.QLineEdit(Form)
        self.lineEditTotalPen.setObjectName("lineEditTotalPen")
        self.horizontalLayout.addWidget(self.lineEditTotalPen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditSugarPrice = QtWidgets.QLineEdit(Form)
        self.lineEditSugarPrice.setObjectName("lineEditSugarPrice")
        self.horizontalLayout_2.addWidget(self.lineEditSugarPrice)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)

        self.doubleSpinBox.editingFinished.connect(self.second_result)

        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.lineEditTotalSugar = QtWidgets.QLineEdit(Form)
        self.lineEditTotalSugar.setObjectName("lineEditTotalSugar")
        self.horizontalLayout_2.addWidget(self.lineEditTotalSugar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.labelResult = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.labelResult.setFont(font)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def first_result(self):
        penPrice = int(self.lineEditPenPrice.text())
        totalPenPrice = self.spinBox.value() * penPrice
        self.lineEditTotalPen.setText(str(totalPenPrice))

    def second_result(self):
        sugarPrice = int(self.lineEditSugarPrice.text())
        totalSugarPrice = self.spinBox.value() * sugarPrice
        self.lineEditTotalSugar.setText(str(totalSugarPrice))

        totalPenPrice = int(self.lineEditTotalPen.text())

        totalAmount = totalPenPrice + totalSugarPrice

        self.labelResult.setText(("Total price is : {} ".format(totalAmount)))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Pen Price: "))
        self.label_2.setText(_translate("Form", "Sugar Price: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
